name: Code Agent Task Request
description: Describe a task for the automated code agent.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a task for the Code Agent!
        Please provide as much detail as possible for the agent to understand and execute the request.
  - type: textarea
    id: task-
    attributes:
      label: Task Description
      description: Clearly describe the code change or task you want the agent to perform. What should it do? What is the goal?
      placeholder: "e.g., Refactor the user service to use the new database connection pool."
    validations:
      required: true
  - type: checkboxes
    id: target-repositories
    attributes:
      label: Target Repositories
      description: Select the repository/repositories where this task should be executed.
      options:
        - label: open-cluster-management-io/ocm
          required: false
        - label: open-cluster-management-io/managed-serviceaccount
          required: false
        - label: open-cluster-management-io/cluster-proxy
          required: false
        - label: stolostron/ocm
          required: false
        - label: stolostron/managed-serviceaccount
          required: false
        - label: stolostron/cluster-proxy
          required: false
        - label: stolostron/managedcluster-import-controller
          required: false
        - label: stolostron/multicloud-operators-foundation
          required: false
        - label: stolostron/cluster-proxy-addon
          required: false
        - label: stolostron/clusterlifecycle-state-metrics
          required: false
        - label: stolostron/klusterlet-addon-controller
          required: false
        - label: stolostron/cluster-lifecycle-api
          required: false
        - label: stolostron/backplane-operator
          required: false
