name: Code Agent Issue Processor

on:
  issues:
    types: [opened, reopened]

permissions:
  contents: write # Needed to checkout code, create branch, push changes, create PR
  pull-requests: write # Needed to create PR
  issues: write # Needed to comment on the issue

# Global environment variables for model selection
env:
  MODS_MODEL: gpt-4o
  CODEX_MODEL: anthropic/claude-3.7-sonnet # The model to use for codex (can be changed globally)
  CODEX_PROVIDER: openrouter

jobs:
  process-issue:
    runs-on: ubuntu-latest
    if: contains('["xuezhaojun", "zhujian7", "qiujian16", "zhiweiyin318", "haoqing0110", "elgnay"]', github.event.issue.user.login)
    steps:
      - name: Get Issue Details
        id: issue_details
        run: |
          echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          echo "ISSUE_BODY<<EOF" >> $GITHUB_OUTPUT
          echo "${{ github.event.issue.body }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "ISSUE_AUTHOR=${{ github.event.issue.user.login }}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Extract checked repositories
        id: extract_information
        run: |
          # Extract checked repositories from the issue body as a JSON array
          REPOS=$(echo "${{ steps.issue_details.outputs.ISSUE_BODY }}" | grep '^\- \[x\]' | sed -E 's/^\- \[x\] //' | jq -R . | jq -s .)
          echo "TARGET_REPOS<<EOF" >> $GITHUB_OUTPUT
          echo "$REPOS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash
    outputs:
      repos: ${{ steps.extract_information.outputs.TARGET_REPOS }}
      ISSUE_NUMBER: ${{ steps.issue_details.outputs.ISSUE_NUMBER }}
      ISSUE_BODY: ${{ steps.issue_details.outputs.ISSUE_BODY }}

  operate-on-repos:
    needs: process-issue
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJson(needs.process-issue.outputs.repos) }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install mods using go install
        run: |
          go install github.com/charmbracelet/mods@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run Codex Agent for repo
        id: codex_agent
        run: |
          set -e # Exit immediately if a command exits with a non-zero status.

          echo "Installing @openai/codex..."
          # latest version has a bug of sanbox issue: https://github.com/openai/codex/issues/782
          npm i -g @openai/codex@0.1.2504251709

          COMMIT_MESSAGE="feat: Automated changes for issue #${{ needs.process-issue.outputs.ISSUE_NUMBER }} in repo ${{ matrix.repo }}"
          AGENT_SUMMARY=""
          AGENT_SUCCESS="false" # Default to failure

          echo "Configuring Git..."
          # Configure git user for commit
          # TODO: Use the actual bot user name and email
          git config --global user.name 'xuezhaojun'
          git config --global user.email 'zxue@redhat.com'

          echo "Cloning repository: xuezhaojun/$REPO_NAME..."
          ORG_REPO="${{ matrix.repo }}"
          REPO_NAME=$(echo "$ORG_REPO" | cut -d'/' -f2)
          git clone https://github.com/xuezhaojun/$REPO_NAME.git
          cd $REPO_NAME
          git fetch origin
          git checkout main || git checkout master
          git pull

          # Use a direct branch name based on issue number and repo
          BRANCH_NAME="code-agent-issue-${{ needs.process-issue.outputs.ISSUE_NUMBER }}-${{ matrix.repo }}-$(date -u +%Y%m%d-%H%M%S)"
          git checkout -b "$BRANCH_NAME"

          echo "--- Task Description ---"
          echo "${{ needs.process-issue.outputs.ISSUE_BODY }}"
          echo "------------------------"
          echo "Running codex for repo: ${{ matrix.repo }}..."

          # Run codex with the issue body as the prompt
          if codex --provider "$CODEX_PROVIDER" --model "$CODEX_MODEL" --approval-mode full-auto --quiet "${{ needs.process-issue.outputs.ISSUE_BODY }}"; then
            echo "Codex completed successfully."
            echo "Staging changes..."
            if git diff --quiet && git diff --staged --quiet; then
              echo "No changes detected by codex."
              AGENT_SUMMARY="Codex ran successfully but made no changes to the code."
              AGENT_SUCCESS="false"
              PR_TITLE="Automated changes for issue #${{ needs.process-issue.outputs.ISSUE_NUMBER }}"
              PR_BODY="No code changes detected."
            else
              echo "Changes detected. Staging..."
              git add .
              git diff --cached > diff.txt

              COMMIT_MSG=$(mods -f --model "$MODS_MODEL" "Generate a concise, conventional commit message (max 1 line, imperative mood, no explanation) based on this git diff. Only output the commit message, no explanation, no code block, no extra text." < diff.txt)
              COMMIT_MSG=$(echo "$COMMIT_MSG" | grep -v '```' | head -n 1)
              if [[ -z "$COMMIT_MSG" ]]; then
                COMMIT_MSG="chore: automated changes for issue #${{ needs.process-issue.outputs.ISSUE_NUMBER }}"
              fi

              echo "Tidying go mod..."
              go mod tidy

              # Check if vendor directory exists and run go mod vendor if it does
              if [ -d "vendor" ]; then
                echo "Vendor directory detected, running go mod vendor..."
                go mod vendor
              fi

              echo "Committing changes..."
              git commit -s -m "$COMMIT_MSG"

              # Use issue title and link for PR
              PR_TITLE="${{ github.event.issue.title }}"
              ISSUE_URL="https://github.com/${{ github.repository }}/issues/${{ needs.process-issue.outputs.ISSUE_NUMBER }}"
              PR_BODY="[Related Issue]($ISSUE_URL)"
              echo "Pushing changes to origin..."
              git remote set-url origin https://xuezhaojun:${GITHUB_TOKEN}@github.com/xuezhaojun/$REPO_NAME.git
              git push origin "$BRANCH_NAME"

              # Generate summary using mods based on issue body and diff
              AGENT_SUMMARY=$(mods -f --model "$MODS_MODEL" "Given the git diff and issue body: ${{ needs.process-issue.outputs.ISSUE_BODY }}, generate a detailed summary in markdown format. Describe what was changed and why these changes were made. Use plain markdown without backticks in headers. Only output the markdown, no explanation." < diff.txt)
              if [[ -z "$AGENT_SUMMARY" ]]; then
                AGENT_SUMMARY="Automated summary for code changes."
              fi

              AGENT_SUCCESS="true"

              # Create PR in the same step instead of a separate step
              echo "Creating Pull Request..."
              ORG=$(echo "$ORG_REPO" | cut -d'/' -f1)
              # Always create PR to upstream repo, head is xuezhaojun:BRANCH_NAME
              gh pr create --repo "$ORG/$REPO_NAME" --base main --head "xuezhaojun:$BRANCH_NAME" --title "$PR_TITLE" --body "$PR_BODY"
            fi
          else
            echo "Codex command failed."
            AGENT_SUMMARY="Codex command failed to execute."
            AGENT_SUCCESS="false"
            PR_TITLE="Automated changes for issue #${{ needs.process-issue.outputs.ISSUE_NUMBER }}"
            PR_BODY="Codex command failed."
          fi

          # Save AGENT_SUMMARY to a file for subsequent steps
          mkdir -p /tmp/workspace
          echo "$AGENT_SUMMARY" > /tmp/workspace/agent_summary.txt

          # Set environment variables for other smaller values
          echo "AGENT_SUCCESS=$AGENT_SUCCESS" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.AGENT_GH_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          GH_TOKEN: ${{ secrets.AGENT_GH_TOKEN }}

      - name: Post Summary Comment on Issue
        if: always()
        run: |
          echo "Posting summary comment..."
          # Read AGENT_SUMMARY from file
          AGENT_SUMMARY=$(cat /tmp/workspace/agent_summary.txt)

          # Create summary with proper newlines (using echo -e to interpret newlines)
          SUMMARY_TITLE="Codex Agent processing complete for Issue #${{ needs.process-issue.outputs.ISSUE_NUMBER }} in repo ${{ matrix.repo }}."
          SUMMARY_CONTENT="Summary: $AGENT_SUMMARY"

          if [[ "${{ env.AGENT_SUCCESS }}" == "true" ]]; then
            PR_URL=$(gh pr view ${{ env.BRANCH_NAME }} --json url -q '.url' || echo "")
            if [[ -n "$PR_URL" ]]; then
              SUMMARY_PR="Pull Request created: ${PR_URL}"
            else
              SUMMARY_PR="Could not retrieve Pull Request URL (it might still be creating or the branch push failed)."
            fi
          elif [[ "${{ env.AGENT_SUCCESS }}" == "false" && -n "$AGENT_SUMMARY" ]]; then
             # If failed, but we have a summary, just show the summary
             SUMMARY_TITLE="Codex Agent processing failed for Issue #${{ needs.process-issue.outputs.ISSUE_NUMBER }} in repo ${{ matrix.repo }}."
             SUMMARY_CONTENT="Summary: $AGENT_SUMMARY"
             SUMMARY_PR=""
          else
             # Generic failure message
             SUMMARY_TITLE="Codex Agent processing failed for Issue #${{ needs.process-issue.outputs.ISSUE_NUMBER }} in repo ${{ matrix.repo }}. Please check the workflow logs for details."
             SUMMARY_CONTENT=""
             SUMMARY_PR=""
          fi

          # Create a properly formatted markdown comment with real newlines
          {
            echo "$SUMMARY_TITLE"
            echo ""
            echo "$SUMMARY_CONTENT"
            if [[ -n "$SUMMARY_PR" ]]; then
              echo ""
              echo "$SUMMARY_PR"
            fi
          } > comment.md

          # Use the file contents for the comment body
          gh issue comment ${{ needs.process-issue.outputs.ISSUE_NUMBER }} --repo "${{ github.repository }}" --body-file comment.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
